version: "3.7"

services:
    frontend:
        image: nginx:alpine
        restart: unless-stopped
        expose:
            - 80
        volumes:
            - build:/usr/share/nginx/html:ro
            - ../.nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - web

volumes:
    build:

networks:
    web:
        external: true