version: "3.7"

services:
    frontend-build:
        build: ../
        volumes:
            - ../:/usr/src/app
            - build:/usr/src/app/build
            - nm:/usr/src/app/node_modules
        networks:
            - web
        command: > # installing dependencies one folder up to keep them in the container and out of the host volume
            sh -c "npm i && npm run build"

volumes:
    nm:
